name: Compile

on: [push]
env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - run: cargo install --git https://github.com/typst/typst typst-cli

      - name: Compiling
        run: typst compile planner.typ

      - name: Archive planner
        uses: actions/upload-artifact@v4
        with:
          name: Upload Planner
          path: planner.pdf

  publish:
    needs: [compile]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish
        uses: actions/download-artifact@v4
        with:
          name: Download Planner
          path: planner.pdf

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Planner compiled
          file_pattern: planner.pdf
